[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/gold-prices"
  to = "/.netlify/functions/gold-prices"
  status = 200

[[redirects]]
  from = "/api/drive-img"
  to = "/.netlify/functions/drive-img"
  status = 200

[[redirects]]
  from = "/api/inventory"
  to = "/.netlify/functions/inventory"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
